Pin clang-tools version to 17.0.6 in nix flake
pq-code-package/mlkem-c-aarch64 pull request #233
Opened 2024-10-14 09:54 UTC by potsrevennil

Signed-off-by: Thing-han, Lim <15379156+potsrevennil@users.noreply.github.com>

2024-10-15 03:10 UTC, hanno-becker requested changes
The change looks innocent, but the CI runtime for the EC2 x86_64 runners seems to drop from ~7 to ~22 min, which I would very much like to avoid if possible.

2024-10-15 04:07 UTC, potsrevennil commented
Yes indeed, I will investigate this further, so please don't merge this PR yet!

2024-10-17 13:50 UTC, hanno-becker commented on .github/actions/setup-nix/action.yml
> +        if [[ ${{ runner.os }} != 'Linux' || $USER == 'root' ]]; then
I think the logic here is not as described in the commit message. The commit message says a Linux root would have single-user mode, but this gives it multi-user mode.

2024-10-17 13:55 UTC, hanno-becker commented on .github/actions/bench/action.yml
> +        gh_token: ${{ inputs.gh_token }}
What's the relevance of those tokens if they are not used for anything?

2024-10-17 14:23 UTC, hanno-becker approved these changes
I must admit that the details of this are out of my depths, and I have to trust you on that @potsrevennil. What I can see though is that everything is _much_ faster now, which is amazing. Makes our development easier and reduces contention and cost on EC2. Bravo!

2024-10-17 14:38 UTC, hanno-becker reviewed
On second thought, I am not comfortable enough with my lack of understanding of the commit which propogates GH access tokens everywhere. Let's discuss this further when you have time again @potsrevennil. I opened https://github.com/pq-code-package/mlkem-c-aarch64/pull/253 to explore if the work is still similarly impactful without token propagation.

2024-10-17 15:06 UTC, hanno-becker commented
Ok, I found https://github.com/NixOS/nix/issues/4653 which explained that authenticated requests have higher rate limit, and that putting the token in `nix.conf` is the recommended way to proceed.

2024-10-17 15:07 UTC, hanno-becker approved these changes

2024-10-17 15:07 UTC, merged